language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libhdf5-dev

before_script:
  - gcc -v
  - g++ -v
  - cmake --version

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

