language: cpp

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/gcc-7.1
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc-7 libhdf5-dev

before_script:
  - gcc-7 -v
  - g++-7 -v
  - cmake --version

env:
  global:
    - CMAKE_CXX_COMPILER=g++-7
    - CMAKE_C_COMPILER=gcc-7

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

